default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: url_shortener_development
  username: <%= ENV['URL_SHORTENER_DATABASE_USERNAME'] %>
  password: <%= ENV['URL_SHORTENER_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: url_shortener_test
  username: <%= ENV['URL_SHORTENER_DATABASE_USERNAME'] %>
  password: <%= ENV['URL_SHORTENER_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: url_shortener_production
  username: <%= ENV['URL_SHORTENER_DATABASE_USERNAME'] %>
  password: <%= ENV['URL_SHORTENER_DATABASE_PASSWORD'] %>
